{
 "title": "Prometheus 2.0 Stats Copy",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Device1 connection status",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "max",
   "targets": [
    { "expr": "devs_mydev1_status" }
   ]
  },
  {
   "title": "Device2 connection status",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 0 },
   "format": "none",
   "valueName": "max",
   "targets": [
    { "expr": "devs_mydev2_status" }
   ]
  },
  {
   "title": "Data Throughput",
   "type": "graph",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 3 },
   "yaxes": [
    { "format": "cps" }
   ],
   "targets": [
    { "expr": "devs_mydev1_tags_tag1", "legendFormat": "{{job}}" }
   ]
  },
  {
   "title": "Data Throughput",
   "type": "graph",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 3 },
   "yaxes": [
    { "format": "cps" }
   ],
   "targets": [
    { "expr": "devs_mydev2_tags_tag1", "legendFormat": "{{job}}" }
   ]
  }
 ]
}