{
 "title": "azuredevice",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Azure Device", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Connection State",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "garyUC8100A_azuredevice_azuredevice1_connectionState{}",
     "legendFormat": "{{desc}}"
    }
   ]
  },
  {
   "title": "Last Desired State",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 3, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "garyUC8100A_azuredevice_azuredevice1_lastDesiredTime{}",
     "legendFormat": "{{desc}}"
    }
   ]
  },
  {
   "title": "D2C Message Queue",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 5, "x": 6, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "garyUC8100A_azuredevice_azuredevice1_d2CMessageQueue{}"
    }
   ]
  },
  {
   "title": "D2C Message Size ",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 11, "y": 1 },
   "targets": [
    {
     "expr": "garyUC8100A_azuredevice_azuredevice1_lastD2CMessageSize{}"
    }
   ]
  },
  {
   "title": "Last Reported State",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 3, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "garyUC8100A_azuredevice_azuredevice1_lastReportedState{}",
     "legendFormat": "{{desc}}"
    }
   ]
  },
  {
   "title": "Last Command State",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 3, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "garyUC8100A_azuredevice_azuredevice1_lastCommandState{}",
     "legendFormat": "{{desc}}"
    }
   ]
  },
  {
   "title": "Last Message Time",
   "type": "stat",
   "gridPos": { "h": 2, "w": 5, "x": 6, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "garyUC8100A_azuredevice_azuredevice1_lastD2CMessageState{}",
     "legendFormat": "{{desc}}"
    }
   ]
  },
  {
   "title": "Message Group 1",
   "type": "stat",
   "gridPos": { "h": 2, "w": 6, "x": 0, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "garyUC8100A_azuredevice1_messageUploader1_connectionState{}",
     "legendFormat": "{{desc}}"
    }
   ]
  },
  {
   "title": "Store&Forward",
   "type": "stat",
   "gridPos": { "h": 2, "w": 6, "x": 6, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "garyUC8100A_azuredevice1_store1_connectionState{}",
     "legendFormat": "{{desc}}"
    }
   ]
  },
  {
   "type": "bargauge",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "garyUC8100A_azuredevice1_messageUploader1_tagsInputQueue{}"
    }
   ]
  },
  {
   "title": "Database Siza (bytes)",
   "type": "bargauge",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "garyUC8100A_azuredevice1_store1_databaseSize{}"
    }
   ]
  },
  {
   "type": "bargauge",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "garyUC8100A_azuredevice1_messageUploader1_bufferTagsCount{}"
    }
   ]
  },
  {
   "title": "Message size in the output buffer ",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "garyUC8100A_azuredevice1_messageUploader1_bufferMessageSize{}"
    }
   ]
  },
  {
   "title": "Last Timer Upload Time",
   "type": "stat",
   "gridPos": { "h": 2, "w": 6, "x": 0, "y": 22 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "garyUC8100A_azuredevice1_messageUploader1_lastTimerTimeoutTime{}",
     "legendFormat": "{{desc}}"
    }
   ]
  }
 ]
}